#!/bin/sh

# user_resources="${HOME}/.config/X11/Xresources"
# user_modmap="${HOME}/.config/X11/Xmodmap"
# sys_resources='/etc/X11/xinit/.Xresources'
# sys_modmap='/etc/X11/xinit/.Xmodmap'

# Merge settings from system files
# if [ -f "${sys_resources}" ]; then
# 	xrdb -merge "$sys_resources"
# fi
# if [ -f "${sys_modmap}" ]; then
# 	xmodmap "${sys_modmap}"
# fi

# Apply user settings
# if [ -f "${user_resources}" ]; then
# 	xrdb "${user_resources}"
# fi
# if [ -f "${user_modmap}" ]; then
# 	xmodmap "${user_modmap}"
# fi

# Set the background color
if [ -f "/home/mkunjummen/Pictures/wallpaper.bmp"] then
	xsetroot -bitmap "/home/mkunjummen/Pictures/wallpaper.bmp"
fi 
# Start xautolock in the background with a 5 minute timer and i3lock
#xautolock -time 15 -locker "i3lock -i '/home/mkunjummen/Pictures/Stormtrooper-wall.png'"

# Start PulseAudio
start-pulseaudio-x11 &

# set the brightness to not death to my eyes level
xbacklight -set 30

# Start i3wm
exec i3
